### ISSUE TITLE
dbt-athena doesn't handle   HIVE_CANNOT_OPEN_SPLIT: File does not exist: errors gracefully

### ISSUE THREAD

**Issue by BeantownData** [Dandandan/dbt-athena#36]
As discussed in the dbt slack (but I can't find it now due to age) Athena queries sometimes return as finished, but the CTAS table file isn't actually ready for querying yet.  The error you get is "HIVE_CANNOT_OPEN_SPLIT: File does not exist".   Running dbt run again usually fixes the problem.

The best way to handle this would probably be to retry a query that fails with this error a set number of times.

Until then, I'm looking at adding in a 1 second wait between DAG nodes.  I've been looking in Lib\site-packages\dbt\adapters\athena\connections.py as the right place to try.  Could I get a clue where to try that?

Thanks!

-Jeff

**Comment by pmleveque** [comment]
This error was related to S3 eventual consistency.
As of Dec. 2020, S3 delivers strong read-after-write consistency, and so this error should appear anymore.

Reference: https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

**Comment by Dandandan** [comment]
Makes sense @pmleveque thanks for updating. If anyone gets this issue, feel free to reopen!
